#!/usr/bin/env tsx
/**
 * Generates an exhaustive list of all valid base pseudo-names from the current
 * wordlists and writes them to name-pool.txt.
 *
 * Re-run whenever adjectives.txt, epic-descriptors.txt, beer-nouns.txt, or
 * beer-styles.txt change:
 *
 *   pnpm --filter @omb/backend generate:names
 *
 * The output file is committed alongside the wordlists — it is a static asset,
 * not a build artifact. Geo prefixes are NOT included here; they are applied
 * at runtime by the generator.
 */
import { readFileSync, writeFileSync, readdirSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const dir = join(__dirname, '../packages/backend/src/lib/pseudo-name')
const outFile = join(dir, 'name-pool.txt')

function loadLines(filename: string): string[] {
  return readFileSync(join(dir, filename), 'utf-8')
    .split('\n')
    .map((s) => s.trim())
    .filter(Boolean)
}

const adjectives = loadLines('adjectives.txt')
const epicWords = loadLines('epic-descriptors.txt')
const beerNouns = loadLines('beer-nouns.txt')
const beerStyles = loadLines('beer-styles.txt')

const MAX_LEN = 20
const names = new Set<string>()

// Template 1: [Adj][BeerNoun]
for (const adj of adjectives) {
  for (const noun of beerNouns) {
    const name = adj + noun
    if (name.length <= MAX_LEN) names.add(name)
  }
}

// Template 2: [Epic][BeerNoun]
for (const epic of epicWords) {
  for (const noun of beerNouns) {
    const name = epic + noun
    if (name.length <= MAX_LEN) names.add(name)
  }
}

// Template 3: [Epic][Adj][BeerStyle] — styles only so brewing roles don't
// end up as the last word in a 3-word name
for (const epic of epicWords) {
  for (const adj of adjectives) {
    for (const style of beerStyles) {
      const name = epic + adj + style
      if (name.length <= MAX_LEN) names.add(name)
    }
  }
}

// Sort alphabetically for stable diffs when wordlists change
const sorted = [...names].sort()

writeFileSync(outFile, sorted.join('\n') + '\n')

console.log(`Generated ${sorted.length} names → ${outFile}`)

// Sanity checks
const overLimit = sorted.filter((n) => n.length > MAX_LEN)
if (overLimit.length > 0) {
  console.error(`ERROR: ${overLimit.length} names exceed ${MAX_LEN} chars:`, overLimit.slice(0, 5))
  process.exit(1)
}
console.log(`Longest name: ${[...sorted].sort((a, b) => b.length - a.length)[0]}`)
console.log(`Shortest name: ${[...sorted].sort((a, b) => a.length - b.length)[0]}`)

// ─── Generate SQL migration for new names ─────────────────────────────────────
//
// Produces a ready-to-commit migration that loads all current names via
// load_pseudo_name_pool().  The function is idempotent — it skips names already
// assigned to users and already present in the pool.
//
// Usage: commit the generated migration alongside name-pool.txt so that the
// next deployment automatically seeds any new names.

const migrationsDir = join(__dirname, '../db/migrations')
const existingVersions = readdirSync(migrationsDir).map((f) => {
  const m = f.match(/^V(\d+)__/)
  return m ? parseInt(m[1], 10) : 0
})
const nextVersion = Math.max(...existingVersions) + 1

const escapedNames = sorted.map((n) => `'${n.replace(/'/g, "''")}'`).join(',\n  ')
const migrationSql =
  `-- Auto-generated by scripts/generate-name-pool.ts\n` +
  `-- Loads all names from the current wordlists that are not yet in the pool.\n` +
  `-- load_pseudo_name_pool() skips names already assigned to users.\n\n` +
  `SELECT load_pseudo_name_pool(ARRAY[\n  ${escapedNames}\n]);\n`

const migrationFile = join(migrationsDir, `V${nextVersion}__load_pseudo_name_pool.sql`)
writeFileSync(migrationFile, migrationSql)
console.log(`Migration written → ${migrationFile}`)
